#!/bin/bash
if [[ -z "$1" ]]; then
	exit 2
fi
BODY=$(echo -ne "$1")
SID=$(cat $HOME/.env_vars/TWILIO_SID)
TOKEN=$(cat $HOME/.env_vars/TWILIO_TOKEN)
TO=$(cat $HOME/.env_vars/PHONE)
FROM=$(cat $HOME/.env_vars/FROM_PHONE)
curl https://api.twilio.com/2010-04-01/Accounts/$SID/Messages.json \
	-X POST \
	--data-urlencode "Body=$BODY" \
	--data-urlencode "From=$FROM" \
	--data-urlencode "To=$TO" \
	-u $SID:$TOKEN \
	&>/dev/null
exit 0
